window.GRAPH = {
  types: [
    { id: "org", label: "Org", color: "#e8ecf4", glow: "#9aa4b8" },
    { id: "team", label: "Team", color: "#5ce1e6", glow: "#2a9aa0" },
    { id: "person", label: "People", color: "#ffc857", glow: "#b8862a" },
    { id: "project", label: "Project", color: "#b794f6", glow: "#6b46c1" },
    { id: "system", label: "System", color: "#34d399", glow: "#059669" },
    { id: "dataset", label: "Dataset", color: "#fb7185", glow: "#e11d48" },
    { id: "model", label: "Model", color: "#60a5fa", glow: "#2563eb" }
  ],
  nodes: [
    { id: "aether", name: "Aether Labs", type: "org", role: "Company", desc: "Frontier research lab building general systems that see, reason, and act.", tags: ["hq", "2021"] },
    { id: "t-research", name: "Research", type: "team", role: "Org unit", desc: "Foundation models, architectures, and eval science.", tags: ["science"] },
    { id: "t-platform", name: "Platform", type: "team", role: "Org unit", desc: "Training stack, inference mesh, and developer surface.", tags: ["eng"] },
    { id: "t-product", name: "Product", type: "team", role: "Org unit", desc: "Ships Helios and Kepler into real workflows.", tags: ["product"] },
    { id: "t-design", name: "Design", type: "team", role: "Org unit", desc: "Interface language for dense, tool-heavy surfaces.", tags: ["design"] },
    { id: "t-infra", name: "Infrastructure", type: "team", role: "Org unit", desc: "Clusters, storage, observability, and capacity.", tags: ["sre"] },
    { id: "t-align", name: "Alignment", type: "team", role: "Org unit", desc: "Oversight, eval gardens, and deployment gates.", tags: ["safety"] },
    { id: "t-applied", name: "Applied Science", type: "team", role: "Org unit", desc: "Domain adapters sitting between research and product.", tags: ["applied"] },
    { id: "p-mira", name: "Mira Chen", type: "person", role: "CEO", desc: "Sets lab direction and the Helios product thesis.", tags: ["exec"] },
    { id: "p-jonas", name: "Jonas Hale", type: "person", role: "CTO", desc: "Owns platform architecture and Trainyard.", tags: ["exec"] },
    { id: "p-priya", name: "Priya Nair", type: "person", role: "Head of Research", desc: "Leads pretraining, scaling laws, and Helios-70B.", tags: ["research"] },
    { id: "p-elias", name: "Elias Voss", type: "person", role: "Head of Platform", desc: "Inference mesh, feature store, and Vector Vault.", tags: ["eng"] },
    { id: "p-amara", name: "Amara Okonkwo", type: "person", role: "Head of Alignment", desc: "Runs Eval Garden and deployment policy.", tags: ["safety"] },
    { id: "p-kenji", name: "Kenji Sato", type: "person", role: "Distinguished Scientist", desc: "Long-horizon reasoning and Kepler-R.", tags: ["research"] },
    { id: "p-lina", name: "Lina Ortega", type: "person", role: "Product Lead", desc: "Helios workspace and agent tools.", tags: ["product"] },
    { id: "p-noah", name: "Noah Berg", type: "person", role: "Infra Lead", desc: "Cluster scheduling and Event Spine.", tags: ["sre"] },
    { id: "p-sofia", name: "Sofia Lind", type: "person", role: "Design Director", desc: "Visual system for Atlas and Loom.", tags: ["design"] },
    { id: "p-rowan", name: "Rowan Ellis", type: "person", role: "Applied Lead", desc: "Nyx vision stack and domain adapters.", tags: ["applied"] },
    { id: "p-tess", name: "Tess Park", type: "person", role: "Research Scientist", desc: "Mixture routing and Prism embeddings.", tags: ["research"] },
    { id: "p-omar", name: "Omar Haddad", type: "person", role: "ML Engineer", desc: "Training recipes and Helios post-train.", tags: ["eng"] },
    { id: "p-yuki", name: "Yuki Tanaka", type: "person", role: "Systems Engineer", desc: "Inferno Mesh runtime and KV cache.", tags: ["eng"] },
    { id: "p-caleb", name: "Caleb Frost", type: "person", role: "Data Engineer", desc: "Lakehouse pipelines and Corpus-X.", tags: ["data"] },
    { id: "p-nadia", name: "Nadia Volkov", type: "person", role: "Eval Lead", desc: "Eval Garden suites and regression gates.", tags: ["safety"] },
    { id: "p-iris", name: "Iris Cho", type: "person", role: "Safety Researcher", desc: "Alignment traces and oversight protocols.", tags: ["safety"] },
    { id: "p-theo", name: "Theo Marks", type: "person", role: "Interface Engineer", desc: "Atlas console and graph surfaces.", tags: ["eng"] },
    { id: "p-vale", name: "Vale Singh", type: "person", role: "SRE", desc: "Aurora observability and on-call.", tags: ["sre"] },
    { id: "x-helios", name: "Helios", type: "project", role: "Flagship", desc: "General assistant with tools, memory, and long context.", tags: ["product", "llm"] },
    { id: "x-nyx", name: "Nyx", type: "project", role: "Vision", desc: "Perception stack for documents, video, and the world.", tags: ["vision"] },
    { id: "x-prism", name: "Prism", type: "project", role: "Retrieval", desc: "Embedding space and hybrid search for the lab.", tags: ["search"] },
    { id: "x-atlas", name: "Atlas", type: "project", role: "Console", desc: "Internal control plane for models, evals, and graphs.", tags: ["ops"] },
    { id: "x-loom", name: "Loom", type: "project", role: "Agents", desc: "Multi-tool agent runtime with human checkpoints.", tags: ["agents"] },
    { id: "x-kepler", name: "Kepler", type: "project", role: "Reasoning", desc: "Slow-thinking specialist for science and code.", tags: ["reason"] },
    { id: "x-solstice", name: "Solstice", type: "project", role: "Eval", desc: "Living benchmark garden and red-team harness.", tags: ["eval"] },
    { id: "s-gate", name: "Gatekeeper", type: "system", role: "Auth", desc: "Identity, policy, and signed tool calls.", tags: ["security"] },
    { id: "s-feat", name: "Feature Store", type: "system", role: "ML", desc: "Online/offline features for routing and memory.", tags: ["ml"] },
    { id: "s-train", name: "Trainyard", type: "system", role: "Training", desc: "Job fabric for pretrain, SFT, and RL.", tags: ["gpu"] },
    { id: "s-infer", name: "Inferno Mesh", type: "system", role: "Serving", desc: "Low-latency replica mesh with speculative decode.", tags: ["serving"] },
    { id: "s-bus", name: "Event Spine", type: "system", role: "Streaming", desc: "Lab-wide event bus for traces and tools.", tags: ["stream"] },
    { id: "s-lake", name: "Lakehouse", type: "system", role: "Storage", desc: "Columnar lake for corpora, logs, and evals.", tags: ["data"] },
    { id: "s-vec", name: "Vector Vault", type: "system", role: "Index", desc: "ANN index backing Prism retrieval.", tags: ["search"] },
    { id: "s-obs", name: "Aurora", type: "system", role: "Observability", desc: "Traces, tokens, and cluster heat.", tags: ["sre"] },
    { id: "d-corpus", name: "Corpus-X", type: "dataset", role: "Pretrain", desc: "Filtered multilingual pretraining mix.", tags: ["text"] },
    { id: "d-night", name: "Nightwatch Logs", type: "dataset", role: "Telemetry", desc: "Production traces used for regression.", tags: ["logs"] },
    { id: "d-eval", name: "Eval Garden", type: "dataset", role: "Benchmarks", desc: "Held-out suites across science, code, and safety.", tags: ["eval"] },
    { id: "d-align", name: "Alignment Traces", type: "dataset", role: "Preference", desc: "Human preference and critique transcripts.", tags: ["rlhf"] },
    { id: "d-synth", name: "SynthLab", type: "dataset", role: "Synthetic", desc: "Generated curricula for post-training.", tags: ["synth"] },
    { id: "d-world", name: "Worldgraph", type: "dataset", role: "Knowledge", desc: "Entity-relation graph feeding Prism.", tags: ["kg"] },
    { id: "m-helios", name: "Helios-70B", type: "model", role: "LLM", desc: "Dense 70B general model, tool-use tuned.", tags: ["70b"] },
    { id: "m-nyx", name: "Nyx-V", type: "model", role: "VLM", desc: "Vision-language backbone for Nyx.", tags: ["vision"] },
    { id: "m-prism", name: "Prism-E", type: "model", role: "Embedding", desc: "Matryoshka embedding model.", tags: ["embed"] },
    { id: "m-kepler", name: "Kepler-R", type: "model", role: "Reasoner", desc: "Long-chain specialist distilled from Helios.", tags: ["cot"] },
    { id: "m-loom", name: "Loom-S", type: "model", role: "Policy", desc: "Small policy model for tool routing.", tags: ["8b"] }
  ],
  links: [
    ["p-mira", "aether", "leads"], ["p-jonas", "aether", "reports to"], ["p-mira", "p-jonas", "partners"],
    ["t-research", "aether", "unit of"], ["t-platform", "aether", "unit of"], ["t-product", "aether", "unit of"],
    ["t-design", "aether", "unit of"], ["t-infra", "aether", "unit of"], ["t-align", "aether", "unit of"], ["t-applied", "aether", "unit of"],
    ["p-priya", "t-research", "leads"], ["p-kenji", "t-research", "member"], ["p-tess", "t-research", "member"],
    ["p-elias", "t-platform", "leads"], ["p-omar", "t-platform", "member"], ["p-yuki", "t-platform", "member"],
    ["p-lina", "t-product", "leads"], ["p-theo", "t-product", "member"], ["p-sofia", "t-design", "leads"],
    ["p-noah", "t-infra", "leads"], ["p-vale", "t-infra", "member"], ["p-caleb", "t-infra", "member"],
    ["p-amara", "t-align", "leads"], ["p-nadia", "t-align", "member"], ["p-iris", "t-align", "member"],
    ["p-rowan", "t-applied", "leads"], ["p-mira", "t-product", "sponsors"], ["p-jonas", "t-platform", "sponsors"], ["p-jonas", "t-infra", "sponsors"],
    ["x-helios", "t-product", "owned by"], ["x-nyx", "t-applied", "owned by"], ["x-prism", "t-research", "owned by"],
    ["x-atlas", "t-platform", "owned by"], ["x-loom", "t-product", "owned by"], ["x-kepler", "t-research", "owned by"], ["x-solstice", "t-align", "owned by"],
    ["p-lina", "x-helios", "owns"], ["p-rowan", "x-nyx", "owns"], ["p-tess", "x-prism", "owns"], ["p-theo", "x-atlas", "builds"],
    ["p-lina", "x-loom", "owns"], ["p-kenji", "x-kepler", "owns"], ["p-nadia", "x-solstice", "owns"],
    ["p-sofia", "x-atlas", "designs"], ["p-sofia", "x-helios", "designs"],
    ["x-loom", "x-helios", "extends"], ["x-kepler", "x-helios", "specializes"], ["x-nyx", "x-helios", "feeds"],
    ["x-prism", "x-helios", "retrieves for"], ["x-solstice", "x-helios", "gates"], ["x-atlas", "x-solstice", "operates"],
    ["s-gate", "t-platform", "run by"], ["s-feat", "t-platform", "run by"], ["s-train", "t-infra", "run by"], ["s-infer", "t-platform", "run by"],
    ["s-bus", "t-infra", "run by"], ["s-lake", "t-infra", "run by"], ["s-vec", "t-platform", "run by"], ["s-obs", "t-infra", "run by"],
    ["p-elias", "s-infer", "owns"], ["p-yuki", "s-infer", "builds"], ["p-noah", "s-train", "owns"], ["p-caleb", "s-lake", "owns"],
    ["p-vale", "s-obs", "owns"], ["p-jonas", "s-gate", "owns"],
    ["x-helios", "s-infer", "serves on"], ["x-helios", "s-gate", "auth via"], ["x-atlas", "s-obs", "reads"],
    ["x-prism", "s-vec", "indexes"], ["x-loom", "s-bus", "emits"], ["s-train", "s-obs", "reports"], ["s-infer", "s-obs", "reports"],
    ["s-feat", "s-lake", "mirrors"], ["s-train", "s-lake", "reads"],
    ["d-corpus", "s-lake", "stored in"], ["d-night", "s-bus", "captured by"], ["d-eval", "x-solstice", "drives"],
    ["d-align", "t-align", "curated by"], ["d-synth", "t-research", "generated by"], ["d-world", "x-prism", "feeds"],
    ["p-caleb", "d-corpus", "owns"], ["p-iris", "d-align", "owns"], ["p-nadia", "d-eval", "owns"], ["p-tess", "d-world", "owns"],
    ["d-night", "s-obs", "feeds"], ["d-synth", "s-train", "used by"],
    ["m-helios", "x-helios", "powers"], ["m-nyx", "x-nyx", "powers"], ["m-prism", "x-prism", "powers"],
    ["m-kepler", "x-kepler", "powers"], ["m-loom", "x-loom", "powers"],
    ["m-helios", "s-train", "trained on"], ["m-helios", "s-infer", "served by"], ["m-helios", "d-corpus", "trained on"], ["m-helios", "d-align", "aligned with"],
    ["m-kepler", "m-helios", "distilled from"], ["m-loom", "m-helios", "distilled from"],
    ["m-nyx", "s-train", "trained on"], ["m-prism", "d-world", "indexes"], ["m-prism", "s-vec", "writes"],
    ["p-priya", "m-helios", "leads"], ["p-kenji", "m-kepler", "leads"], ["p-omar", "m-helios", "trains"], ["p-rowan", "m-nyx", "leads"]
  ]
};
